name: 'Deploy K8s Application'
description: 'Greet someone'
branding:
  icon: upload-cloud
  color: blue
inputs:
  install_local_cluster:
    description: 'To Create Local K3D Cluster'
    required: false
    default: "false"
  local_cluster_name:
    description: 'Name of Cluster if using K3d Local cluster'
    required: false
    default: "mycluster"    
  local_cluster_args:
    description: 'Args if using K3d Local Cluster'
    required: false
    default: >-
      -p "8080:80@loadbalancer"
      -p "9443:443@loadbalancer"
      --api-port 6443
      --servers 1
      --agents 1
      --verbose 
      --k3s-node-label "node=ondemand@server:0;agent:0"
      --k3s-arg "--disable=traefik@server:0"      
  kubeconfig:
    description: 'Kubernetes Cluster Configuration File'
    required: false
    default: '/home/runner/.kube/config'
  charts:
    description: "Helm Charts to deploy. Using the following Yaml Syntax"
    required: false
runs:
  using: "composite"
  steps:
    - name: "create k3d cluster"
      if: ${{ fromJSON(inputs.install_local_cluster) }}
      uses: AbsaOSS/k3d-action@v2.3.0
      with:
        cluster-name: ${{inputs.local_cluster_name}}
        args: ${{inputs.local_cluster_args}}
    - name: Generate KUBECONFIG File
      run: |
        if [[ ${{ fromJSON(inputs.install_local_cluster) }} ]]
        then
          echo "::set-output name=kubeconfig::$(cat $HOME/.kube/config)"        
        else
          echo "::set-output name=kubeconfig::$(echo ${{inputs.kubeconfig}})"
        fi        
      shell: bash
    - run: python3 -m pip install gitpython
      shell: bash
    - run: python3 ${{ github.action_path }}/script.py
      shell: bash
      env:
        KUBECONFIG: ${{ steps.kubeconfig.outputs.kubeconfig }}
        CHARTS: ${{ inputs.charts }}