name: 'Deploy K8s Application'
description: 'Greet someone'
branding:
  icon: upload-cloud
  color: blue
inputs:
  kubeconfig:
    description: 'Kubernetes Cluster Configuration File'
    required: true
    default: '/home/runner/.kube/config'
  args:
    description: "Helm Charts to deploy"
    required: false
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    # - id: random-number-generator
    #   run: echo "::set-output name=random-number::$(echo $RANDOM)"
    #   shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash          
    - run: goodbye.sh
      shell: bash